HouseSharing/Controllers/PropertyController.cs
using HouseSharing.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HouseSharing.Controllers
{
    public class PropertyController : Controller
    {
        private HouseSharingEntities _db = new HouseSharingEntities();

        // GET: Property
        public ActionResult Index()
        {
            Bien model = new Bien()
            {
                Countries = _db.Countries.ToList(),
                Categories = _db.Categories.ToList()
            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Index(Bien p, IEnumerable<HttpPostedFileBase> uploads)
        {
            foreach (var photo in uploads)
            {
                string name = Guid.NewGuid().ToString() + photo.FileName;
                photo.SaveAs(HttpContext.Server.MapPath(string.Format("~/Content/Photos/{0}", name)));
                p.Photos.Add(new Photo() { Name = name });

            }
            p.UserID = Infra.Utils.ConnectedUSer.ID;
            _db.Options.Add(p.Option);
            _db.SaveChanges();
            _db.Biens.Add(p);
            _db.SaveChanges();
            
            return RedirectToAction("BienCreated");
        }

        public ActionResult BienCreated()
        {
            //ajout de commentaire
            return View();
        }

        public ActionResult Details(int ID)
        {
            Bien model = _db.Biens.Where(b => b.ID == ID).FirstOrDefault();
            return View(model);
        }
    }
}

HouseSharing/Views/Property/BienCreated.cshtml

@{
    ViewBag.Title = "BienCreated";
}

<h2>Thank you, your property has been registered</h2>


HouseSharing/Views/Property/Details.cshtml
@model HouseSharing.Models.Bien

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div style="width:80vw; margin: auto;">
    <img style="width:100%; height:auto;" src="~/Content/Photos/@Model.Photos.FirstOrDefault().Name" /> <br /><br />

</div>

<p style="margin-left:9vw; margin-right: 9vw;">
    <strong>@Html.DisplayFor(modelItem => Model.Category.Name)</strong> <br />
    Adresse: @Html.DisplayFor(modelItem => Model.Adresse),
    @Html.DisplayFor(modelItem => Model.City),
    @Html.DisplayFor(modelItem => Model.Country.Name)
</p>

<table style="margin-left:9vw; margin-right: 9vw;" class="detailsBien">
    <tr>
        <td class="description">
            @Html.DisplayFor(modelItem => Model.Description) <br /><br />
            @foreach (var item in @Model.Photos)
            {
                <img style="width:18vw; height:auto;" src="~/Content/Photos/@item.Name" />
            }
        </td>

        <td class="options">
            <strong>Prix: @Html.DisplayFor(modelItem => Model.PricePerNight) euro</strong> <br /><br />


            @if (Model.Option.Surface != 0)
            {
                <p>Surface: @Model.Option.Surface</p>
            }
            @if (Model.Option.Rooms != 0)
            {
                <p>Rooms: @Model.Option.Rooms</p>
            }
            @if (Model.Option.Bathrooms != 0)
            {
                <p>Bathrooms: @Model.Option.Bathrooms</p>
            }
            <br />
            @if (Model.Option.BabyBed)
            {
                <p>@Html.DisplayFor(modelItem => Model.Option.BabyBed) Baby Bed </p>
            }
            @if (Model.Option.DishWasher)
            {
                <p>@Html.DisplayFor(modelItem => Model.Option.DishWasher) Dish Washer </p>
            }
            @if (Model.Option.Garage)
            {
                <p>@Html.DisplayFor(modelItem => Model.Option.Garage) Garage</p>
            }
            @if (Model.Option.Garden)
            {
                <p>@Html.DisplayFor(modelItem => Model.Option.Garden) Garden</p>
            }
            @if (Model.Option.Terrace)
            {
                <p>@Html.DisplayFor(modelItem => Model.Option.Terrace) Terrace</p>
            }
            @if (Model.Option.WashingMachine)
            {
                <p>@Html.DisplayFor(modelItem => Model.Option.WashingMachine) Washing Machine</p>
            }
            
            <br /><br />
            
            <input style="margin-left: 2vw; background-color: aquamarine;" type="submit" name="submit" value="Rent" />

        </td>
    </tr>
</table>








HouseSharing/Views/Property/Index.cshtml
@model HouseSharing.Models.Bien

@{
    ViewBag.Title = "Index";
}

<h2>New Property</h2>

@using (Html.BeginForm("Index", "Property", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()

    <div style="margin-left:30vw;" class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Adresse, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adresse, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adresse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Country.Name, "Country", htmlAttributes: new { @class = "control-label col-md-2 formLabel" })
            <div class="col-md-10 inputForm">
                <select name="CountryID" class="form-control">
                    @foreach (var item in Model.Countries)
                    {
                    <option value="@item.ID">@item.Name</option>}
                </select>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category.Name, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10 inputForm">
                <select name="CategoryID" class="form-control">
                    @foreach (var item in Model.Categories)
                    {
                    <option value="@item.ID">@item.Name</option>}
                </select>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option.Surface, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="number" name="Option.Surface" class="form-control" />
                @Html.ValidationMessageFor(model => model.Option.Surface, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option.Rooms, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="number" name="Option.Rooms" />
                @Html.ValidationMessageFor(model => model.Option.Rooms, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option.Bathrooms, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="number" name="Option.Bathrooms" />
                @Html.ValidationMessageFor(model => model.Option.Bathrooms, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option.BabyBed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.Option.BabyBed)
                @Html.ValidationMessageFor(model => model.Option.BabyBed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option.DishWasher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.Option.DishWasher)
                @Html.ValidationMessageFor(model => model.Option.DishWasher, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option.Garage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.Option.Garage)
                @Html.ValidationMessageFor(model => model.Option.Garage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option.Garden, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.Option.Garden)
                @Html.ValidationMessageFor(model => model.Option.Garden, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option.Terrace, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.Option.Terrace)
                @Html.ValidationMessageFor(model => model.Option.Terrace, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Option.WashingMachine, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(model => model.Option.WashingMachine)
                @Html.ValidationMessageFor(model => model.Option.WashingMachine, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PricePerNight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PricePerNight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PricePerNight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group addPhotos">
            @Html.LabelFor(model => model.Photos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="uploads" />
                @Html.ValidationMessageFor(model => model.Photos, "", new { @class = "text-danger" })
            </div>
        </div>
        <div id="buttonAdd"><button id="addPhoto" type="button">Add photo</button></div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@section scripts{
<script>
    $("#addPhoto").click(function (e) {
        $(".addPhotos:first").clone().insertBefore("#addPhoto");
    });
</script>
}